/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CypherUiModule extends AbstractCypherUiModule {

	public CypherUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
