/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.s2c.cypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create Relationship Property Existence Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.s2c.cypher.CypherPackage#getCreateRelationshipPropertyExistenceConstraint()
 * @model
 * @generated
 */
public interface CreateRelationshipPropertyExistenceConstraint extends Command
{
} // CreateRelationshipPropertyExistenceConstraint
