/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.s2c.cypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>In Query Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.s2c.cypher.InQueryCall#getInvocation <em>Invocation</em>}</li>
 *   <li>{@link org.xtext.example.s2c.cypher.InQueryCall#getYieldItems <em>Yield Items</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.s2c.cypher.CypherPackage#getInQueryCall()
 * @model
 * @generated
 */
public interface InQueryCall extends ReadingClause
{
  /**
   * Returns the value of the '<em><b>Invocation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Invocation</em>' containment reference.
   * @see #setInvocation(ExplicitProcedureInvocation)
   * @see org.xtext.example.s2c.cypher.CypherPackage#getInQueryCall_Invocation()
   * @model containment="true"
   * @generated
   */
  ExplicitProcedureInvocation getInvocation();

  /**
   * Sets the value of the '{@link org.xtext.example.s2c.cypher.InQueryCall#getInvocation <em>Invocation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Invocation</em>' containment reference.
   * @see #getInvocation()
   * @generated
   */
  void setInvocation(ExplicitProcedureInvocation value);

  /**
   * Returns the value of the '<em><b>Yield Items</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Yield Items</em>' containment reference.
   * @see #setYieldItems(YieldItems)
   * @see org.xtext.example.s2c.cypher.CypherPackage#getInQueryCall_YieldItems()
   * @model containment="true"
   * @generated
   */
  YieldItems getYieldItems();

  /**
   * Sets the value of the '{@link org.xtext.example.s2c.cypher.InQueryCall#getYieldItems <em>Yield Items</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Yield Items</em>' containment reference.
   * @see #getYieldItems()
   * @generated
   */
  void setYieldItems(YieldItems value);

} // InQueryCall
