/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.s2c.cypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Is Not Null Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.s2c.cypher.CypherPackage#getIsNotNullExpression()
 * @model
 * @generated
 */
public interface IsNotNullExpression extends Expression
{
} // IsNotNullExpression
