/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.s2c.cypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Query</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.s2c.cypher.CypherPackage#getSingleQuery()
 * @model
 * @generated
 */
public interface SingleQuery extends RegularQuery
{
} // SingleQuery
