/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.cypher.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.cypher.CypherPackage;
import org.xtext.example.mydsl.cypher.RemoveItem;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Remove Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RemoveItemImpl extends NodeLabelsImpl implements RemoveItem
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RemoveItemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CypherPackage.Literals.REMOVE_ITEM;
  }

} //RemoveItemImpl
