/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl1.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>All Options</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.AllOptions#isExplain <em>Explain</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.AllOptions#isProfile <em>Profile</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.AllOptions#getCypherOption <em>Cypher Option</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getAllOptions()
 * @model
 * @generated
 */
public interface AllOptions extends QueryOptions
{
  /**
   * Returns the value of the '<em><b>Explain</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Explain</em>' attribute.
   * @see #setExplain(boolean)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getAllOptions_Explain()
   * @model
   * @generated
   */
  boolean isExplain();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.AllOptions#isExplain <em>Explain</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Explain</em>' attribute.
   * @see #isExplain()
   * @generated
   */
  void setExplain(boolean value);

  /**
   * Returns the value of the '<em><b>Profile</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Profile</em>' attribute.
   * @see #setProfile(boolean)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getAllOptions_Profile()
   * @model
   * @generated
   */
  boolean isProfile();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.AllOptions#isProfile <em>Profile</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Profile</em>' attribute.
   * @see #isProfile()
   * @generated
   */
  void setProfile(boolean value);

  /**
   * Returns the value of the '<em><b>Cypher Option</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl1.myDsl.CypherOption}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cypher Option</em>' containment reference list.
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getAllOptions_CypherOption()
   * @model containment="true"
   * @generated
   */
  EList<CypherOption> getCypherOption();

} // AllOptions
