/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl1.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Anonymous Pattern Part</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getAnonymousPatternPart()
 * @model
 * @generated
 */
public interface AnonymousPatternPart extends PatternPart
{
} // AnonymousPatternPart
