/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl1.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Drop Node Property Existence Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.DropNodePropertyExistenceConstraint#getNodePropertyExistenceConstraint <em>Node Property Existence Constraint</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getDropNodePropertyExistenceConstraint()
 * @model
 * @generated
 */
public interface DropNodePropertyExistenceConstraint extends Command
{
  /**
   * Returns the value of the '<em><b>Node Property Existence Constraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node Property Existence Constraint</em>' containment reference.
   * @see #setNodePropertyExistenceConstraint(NodePropertyExistenceConstraint)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getDropNodePropertyExistenceConstraint_NodePropertyExistenceConstraint()
   * @model containment="true"
   * @generated
   */
  NodePropertyExistenceConstraint getNodePropertyExistenceConstraint();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.DropNodePropertyExistenceConstraint#getNodePropertyExistenceConstraint <em>Node Property Existence Constraint</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node Property Existence Constraint</em>' containment reference.
   * @see #getNodePropertyExistenceConstraint()
   * @generated
   */
  void setNodePropertyExistenceConstraint(NodePropertyExistenceConstraint value);

} // DropNodePropertyExistenceConstraint
