/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl1.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Load CSV Query</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.LoadCSVQuery#getLoadCSV <em>Load CSV</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.LoadCSVQuery#getSingleQuery <em>Single Query</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getLoadCSVQuery()
 * @model
 * @generated
 */
public interface LoadCSVQuery extends EObject
{
  /**
   * Returns the value of the '<em><b>Load CSV</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Load CSV</em>' containment reference.
   * @see #setLoadCSV(LoadCSV)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getLoadCSVQuery_LoadCSV()
   * @model containment="true"
   * @generated
   */
  LoadCSV getLoadCSV();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.LoadCSVQuery#getLoadCSV <em>Load CSV</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Load CSV</em>' containment reference.
   * @see #getLoadCSV()
   * @generated
   */
  void setLoadCSV(LoadCSV value);

  /**
   * Returns the value of the '<em><b>Single Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Single Query</em>' containment reference.
   * @see #setSingleQuery(SingleQuery)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getLoadCSVQuery_SingleQuery()
   * @model containment="true"
   * @generated
   */
  SingleQuery getSingleQuery();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.LoadCSVQuery#getSingleQuery <em>Single Query</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Single Query</em>' containment reference.
   * @see #getSingleQuery()
   * @generated
   */
  void setSingleQuery(SingleQuery value);

} // LoadCSVQuery
