/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl1.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pattern Comprehension</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.PatternComprehension#getPathVariable <em>Path Variable</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.PatternComprehension#getPattern <em>Pattern</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.PatternComprehension#getWhere <em>Where</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.PatternComprehension#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getPatternComprehension()
 * @model
 * @generated
 */
public interface PatternComprehension extends Expression
{
  /**
   * Returns the value of the '<em><b>Path Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path Variable</em>' containment reference.
   * @see #setPathVariable(VariableDeclaration)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getPatternComprehension_PathVariable()
   * @model containment="true"
   * @generated
   */
  VariableDeclaration getPathVariable();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.PatternComprehension#getPathVariable <em>Path Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path Variable</em>' containment reference.
   * @see #getPathVariable()
   * @generated
   */
  void setPathVariable(VariableDeclaration value);

  /**
   * Returns the value of the '<em><b>Pattern</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern</em>' containment reference.
   * @see #setPattern(RelationshipsPattern)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getPatternComprehension_Pattern()
   * @model containment="true"
   * @generated
   */
  RelationshipsPattern getPattern();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.PatternComprehension#getPattern <em>Pattern</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pattern</em>' containment reference.
   * @see #getPattern()
   * @generated
   */
  void setPattern(RelationshipsPattern value);

  /**
   * Returns the value of the '<em><b>Where</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Where</em>' containment reference.
   * @see #setWhere(Where)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getPatternComprehension_Where()
   * @model containment="true"
   * @generated
   */
  Where getWhere();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.PatternComprehension#getWhere <em>Where</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Where</em>' containment reference.
   * @see #getWhere()
   * @generated
   */
  void setWhere(Where value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getPatternComprehension_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.PatternComprehension#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

} // PatternComprehension
