/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl1.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relationship Lookup</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getRelationshipLookup()
 * @model
 * @generated
 */
public interface RelationshipLookup extends Lookup
{
} // RelationshipLookup
