/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.s2c.cypher.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.s2c.cypher.CypherPackage;
import org.xtext.example.s2c.cypher.IsNotNullExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Is Not Null Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IsNotNullExpressionImpl extends ExpressionImpl implements IsNotNullExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IsNotNullExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CypherPackage.Literals.IS_NOT_NULL_EXPRESSION;
  }

} //IsNotNullExpressionImpl
