/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.s2c.cypher.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.s2c.cypher.CypherPackage;
import org.xtext.example.s2c.cypher.QueryOptions;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Query Options</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class QueryOptionsImpl extends MinimalEObjectImpl.Container implements QueryOptions
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QueryOptionsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CypherPackage.Literals.QUERY_OPTIONS;
  }

} //QueryOptionsImpl
