/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl1.ui.tests;

import com.google.inject.Injector;
import cyphet.ui.internal.CyphetActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CyphetActivator.getInstance().getInjector("org.xtext.example.mydsl1.MyDsl");
	}

}
