/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.cypher;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Case Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.cypher.CaseExpression#getCaseAlternatives <em>Case Alternatives</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.cypher.CaseExpression#getCaseExpression <em>Case Expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.cypher.CaseExpression#getElseExpression <em>Else Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.cypher.CypherPackage#getCaseExpression()
 * @model
 * @generated
 */
public interface CaseExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Case Alternatives</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.cypher.CaseAlternatives}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Case Alternatives</em>' containment reference list.
   * @see org.xtext.example.mydsl.cypher.CypherPackage#getCaseExpression_CaseAlternatives()
   * @model containment="true"
   * @generated
   */
  EList<CaseAlternatives> getCaseAlternatives();

  /**
   * Returns the value of the '<em><b>Case Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Case Expression</em>' containment reference.
   * @see #setCaseExpression(Expression)
   * @see org.xtext.example.mydsl.cypher.CypherPackage#getCaseExpression_CaseExpression()
   * @model containment="true"
   * @generated
   */
  Expression getCaseExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.cypher.CaseExpression#getCaseExpression <em>Case Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Case Expression</em>' containment reference.
   * @see #getCaseExpression()
   * @generated
   */
  void setCaseExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Else Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else Expression</em>' containment reference.
   * @see #setElseExpression(Expression)
   * @see org.xtext.example.mydsl.cypher.CypherPackage#getCaseExpression_ElseExpression()
   * @model containment="true"
   * @generated
   */
  Expression getElseExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.cypher.CaseExpression#getElseExpression <em>Else Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else Expression</em>' containment reference.
   * @see #getElseExpression()
   * @generated
   */
  void setElseExpression(Expression value);

} // CaseExpression
