/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.cypher;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.cypher.Delete#isDetach <em>Detach</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.cypher.Delete#getExpressions <em>Expressions</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.cypher.CypherPackage#getDelete()
 * @model
 * @generated
 */
public interface Delete extends UpdatingClause
{
  /**
   * Returns the value of the '<em><b>Detach</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Detach</em>' attribute.
   * @see #setDetach(boolean)
   * @see org.xtext.example.mydsl.cypher.CypherPackage#getDelete_Detach()
   * @model
   * @generated
   */
  boolean isDetach();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.cypher.Delete#isDetach <em>Detach</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Detach</em>' attribute.
   * @see #isDetach()
   * @generated
   */
  void setDetach(boolean value);

  /**
   * Returns the value of the '<em><b>Expressions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.cypher.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions</em>' containment reference list.
   * @see org.xtext.example.mydsl.cypher.CypherPackage#getDelete_Expressions()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getExpressions();

} // Delete
