/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.cypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node Lookup</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.cypher.CypherPackage#getNodeLookup()
 * @model
 * @generated
 */
public interface NodeLookup extends Lookup
{
} // NodeLookup
