/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.cypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>NULL</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.cypher.CypherPackage#getNULL()
 * @model
 * @generated
 */
public interface NULL extends Literal
{
} // NULL
