/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.cypher;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Range Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.cypher.RangeLiteral#getLower <em>Lower</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.cypher.RangeLiteral#isVariableLength <em>Variable Length</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.cypher.RangeLiteral#getUpper <em>Upper</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.cypher.CypherPackage#getRangeLiteral()
 * @model
 * @generated
 */
public interface RangeLiteral extends EObject
{
  /**
   * Returns the value of the '<em><b>Lower</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lower</em>' attribute.
   * @see #setLower(String)
   * @see org.xtext.example.mydsl.cypher.CypherPackage#getRangeLiteral_Lower()
   * @model
   * @generated
   */
  String getLower();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.cypher.RangeLiteral#getLower <em>Lower</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lower</em>' attribute.
   * @see #getLower()
   * @generated
   */
  void setLower(String value);

  /**
   * Returns the value of the '<em><b>Variable Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Length</em>' attribute.
   * @see #setVariableLength(boolean)
   * @see org.xtext.example.mydsl.cypher.CypherPackage#getRangeLiteral_VariableLength()
   * @model
   * @generated
   */
  boolean isVariableLength();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.cypher.RangeLiteral#isVariableLength <em>Variable Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable Length</em>' attribute.
   * @see #isVariableLength()
   * @generated
   */
  void setVariableLength(boolean value);

  /**
   * Returns the value of the '<em><b>Upper</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Upper</em>' attribute.
   * @see #setUpper(String)
   * @see org.xtext.example.mydsl.cypher.CypherPackage#getRangeLiteral_Upper()
   * @model
   * @generated
   */
  String getUpper();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.cypher.RangeLiteral#getUpper <em>Upper</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Upper</em>' attribute.
   * @see #getUpper()
   * @generated
   */
  void setUpper(String value);

} // RangeLiteral
