/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl1.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import sql.ui.internal.SqlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SqlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SqlActivator activator = SqlActivator.getInstance();
		return activator != null ? activator.getInjector(SqlActivator.ORG_XTEXT_EXAMPLE_MYDSL1_MYDSL) : null;
	}

}
