/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.SqlRuntimeModule;
import org.xtext.example.mydsl.SqlStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SqlIdeSetup extends SqlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SqlRuntimeModule(), new SqlIdeModule()));
	}
	
}
