/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.s2c.sQL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>from Section</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.s2c.sQL.fromSection#getFrom_item <em>From item</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.s2c.sQL.SQLPackage#getfromSection()
 * @model
 * @generated
 */
public interface fromSection extends EObject
{
  /**
   * Returns the value of the '<em><b>From item</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From item</em>' containment reference.
   * @see #setFrom_item(fromItem)
   * @see org.xtext.example.s2c.sQL.SQLPackage#getfromSection_From_item()
   * @model containment="true"
   * @generated
   */
  fromItem getFrom_item();

  /**
   * Sets the value of the '{@link org.xtext.example.s2c.sQL.fromSection#getFrom_item <em>From item</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From item</em>' containment reference.
   * @see #getFrom_item()
   * @generated
   */
  void setFrom_item(fromItem value);

} // fromSection
