/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.s2c.sQL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.s2c.sQL.SQLFactory
 * @model kind="package"
 * @generated
 */
public interface SQLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "sQL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/s2c/SQL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "sQL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SQLPackage eINSTANCE = org.xtext.example.s2c.sQL.impl.SQLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.s2c.sQL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.s2c.sQL.impl.ModelImpl
   * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.s2c.sQL.impl.selectImpl <em>select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.s2c.sQL.impl.selectImpl
   * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getselect()
   * @generated
   */
  int SELECT = 1;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__EXPRESSIONS = 0;

  /**
   * The feature id for the '<em><b>From section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__FROM_SECTION = 1;

  /**
   * The feature id for the '<em><b>Where section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__WHERE_SECTION = 2;

  /**
   * The feature id for the '<em><b>Group section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__GROUP_SECTION = 3;

  /**
   * The feature id for the '<em><b>Having section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__HAVING_SECTION = 4;

  /**
   * The number of structural features of the '<em>select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.s2c.sQL.impl.fromSectionImpl <em>from Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.s2c.sQL.impl.fromSectionImpl
   * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getfromSection()
   * @generated
   */
  int FROM_SECTION = 2;

  /**
   * The feature id for the '<em><b>From item</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FROM_SECTION__FROM_ITEM = 0;

  /**
   * The number of structural features of the '<em>from Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FROM_SECTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.s2c.sQL.impl.fromItemImpl <em>from Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.s2c.sQL.impl.fromItemImpl
   * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getfromItem()
   * @generated
   */
  int FROM_ITEM = 3;

  /**
   * The feature id for the '<em><b>Table name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FROM_ITEM__TABLE_NAME = 0;

  /**
   * The feature id for the '<em><b>Select expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FROM_ITEM__SELECT_EXPR = 1;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FROM_ITEM__RHS = 2;

  /**
   * The feature id for the '<em><b>Bool expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FROM_ITEM__BOOL_EXPR = 3;

  /**
   * The number of structural features of the '<em>from Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FROM_ITEM_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.s2c.sQL.impl.where_clauseImpl <em>where clause</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.s2c.sQL.impl.where_clauseImpl
   * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getwhere_clause()
   * @generated
   */
  int WHERE_CLAUSE = 4;

  /**
   * The feature id for the '<em><b>Bool expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_CLAUSE__BOOL_EXPR = 0;

  /**
   * The number of structural features of the '<em>where clause</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_CLAUSE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.s2c.sQL.impl.boolExpressionImpl <em>bool Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.s2c.sQL.impl.boolExpressionImpl
   * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getboolExpression()
   * @generated
   */
  int BOOL_EXPRESSION = 5;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_EXPRESSION__LHS = 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_EXPRESSION__RHS = 1;

  /**
   * The number of structural features of the '<em>bool Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.s2c.sQL.impl.TermImpl <em>Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.s2c.sQL.impl.TermImpl
   * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getTerm()
   * @generated
   */
  int TERM = 6;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM__LHS = 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM__RHS = 1;

  /**
   * The number of structural features of the '<em>Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.s2c.sQL.impl.FactorImpl <em>Factor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.s2c.sQL.impl.FactorImpl
   * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getFactor()
   * @generated
   */
  int FACTOR = 7;

  /**
   * The feature id for the '<em><b>Factor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR__FACTOR = 0;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR__EXPR = 1;

  /**
   * The feature id for the '<em><b>Binexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR__BINEXP = 2;

  /**
   * The number of structural features of the '<em>Factor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.s2c.sQL.impl.BinaryImpl <em>Binary</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.s2c.sQL.impl.BinaryImpl
   * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getBinary()
   * @generated
   */
  int BINARY = 8;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY__LHS = 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY__RHS = 1;

  /**
   * The number of structural features of the '<em>Binary</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.s2c.sQL.impl.ColumnImpl <em>Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.s2c.sQL.impl.ColumnImpl
   * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getColumn()
   * @generated
   */
  int COLUMN = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__NAME = 0;

  /**
   * The number of structural features of the '<em>Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.s2c.sQL.impl.group_clauseImpl <em>group clause</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.s2c.sQL.impl.group_clauseImpl
   * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getgroup_clause()
   * @generated
   */
  int GROUP_CLAUSE = 10;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_CLAUSE__EXPRESSIONS = 0;

  /**
   * The number of structural features of the '<em>group clause</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_CLAUSE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.s2c.sQL.impl.having_clauseImpl <em>having clause</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.s2c.sQL.impl.having_clauseImpl
   * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#gethaving_clause()
   * @generated
   */
  int HAVING_CLAUSE = 11;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HAVING_CLAUSE__EXPR = 0;

  /**
   * The number of structural features of the '<em>having clause</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HAVING_CLAUSE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.s2c.sQL.impl.expressionImpl <em>expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.s2c.sQL.impl.expressionImpl
   * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getexpression()
   * @generated
   */
  int EXPRESSION = 12;

  /**
   * The feature id for the '<em><b>Col</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__COL = 0;

  /**
   * The number of structural features of the '<em>expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.s2c.sQL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.s2c.sQL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.s2c.sQL.Model#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.xtext.example.s2c.sQL.Model#getStatements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Statements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.s2c.sQL.select <em>select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>select</em>'.
   * @see org.xtext.example.s2c.sQL.select
   * @generated
   */
  EClass getselect();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.s2c.sQL.select#getExpressions <em>Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressions</em>'.
   * @see org.xtext.example.s2c.sQL.select#getExpressions()
   * @see #getselect()
   * @generated
   */
  EReference getselect_Expressions();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.select#getFrom_section <em>From section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>From section</em>'.
   * @see org.xtext.example.s2c.sQL.select#getFrom_section()
   * @see #getselect()
   * @generated
   */
  EReference getselect_From_section();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.select#getWhere_section <em>Where section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Where section</em>'.
   * @see org.xtext.example.s2c.sQL.select#getWhere_section()
   * @see #getselect()
   * @generated
   */
  EReference getselect_Where_section();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.select#getGroup_section <em>Group section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Group section</em>'.
   * @see org.xtext.example.s2c.sQL.select#getGroup_section()
   * @see #getselect()
   * @generated
   */
  EReference getselect_Group_section();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.select#getHaving_section <em>Having section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Having section</em>'.
   * @see org.xtext.example.s2c.sQL.select#getHaving_section()
   * @see #getselect()
   * @generated
   */
  EReference getselect_Having_section();

  /**
   * Returns the meta object for class '{@link org.xtext.example.s2c.sQL.fromSection <em>from Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>from Section</em>'.
   * @see org.xtext.example.s2c.sQL.fromSection
   * @generated
   */
  EClass getfromSection();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.fromSection#getFrom_item <em>From item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>From item</em>'.
   * @see org.xtext.example.s2c.sQL.fromSection#getFrom_item()
   * @see #getfromSection()
   * @generated
   */
  EReference getfromSection_From_item();

  /**
   * Returns the meta object for class '{@link org.xtext.example.s2c.sQL.fromItem <em>from Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>from Item</em>'.
   * @see org.xtext.example.s2c.sQL.fromItem
   * @generated
   */
  EClass getfromItem();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.s2c.sQL.fromItem#getTable_name <em>Table name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Table name</em>'.
   * @see org.xtext.example.s2c.sQL.fromItem#getTable_name()
   * @see #getfromItem()
   * @generated
   */
  EAttribute getfromItem_Table_name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.fromItem#getSelect_expr <em>Select expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Select expr</em>'.
   * @see org.xtext.example.s2c.sQL.fromItem#getSelect_expr()
   * @see #getfromItem()
   * @generated
   */
  EReference getfromItem_Select_expr();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.fromItem#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.s2c.sQL.fromItem#getRhs()
   * @see #getfromItem()
   * @generated
   */
  EReference getfromItem_Rhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.fromItem#getBool_expr <em>Bool expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bool expr</em>'.
   * @see org.xtext.example.s2c.sQL.fromItem#getBool_expr()
   * @see #getfromItem()
   * @generated
   */
  EReference getfromItem_Bool_expr();

  /**
   * Returns the meta object for class '{@link org.xtext.example.s2c.sQL.where_clause <em>where clause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>where clause</em>'.
   * @see org.xtext.example.s2c.sQL.where_clause
   * @generated
   */
  EClass getwhere_clause();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.where_clause#getBool_expr <em>Bool expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bool expr</em>'.
   * @see org.xtext.example.s2c.sQL.where_clause#getBool_expr()
   * @see #getwhere_clause()
   * @generated
   */
  EReference getwhere_clause_Bool_expr();

  /**
   * Returns the meta object for class '{@link org.xtext.example.s2c.sQL.boolExpression <em>bool Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>bool Expression</em>'.
   * @see org.xtext.example.s2c.sQL.boolExpression
   * @generated
   */
  EClass getboolExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.boolExpression#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.s2c.sQL.boolExpression#getLhs()
   * @see #getboolExpression()
   * @generated
   */
  EReference getboolExpression_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.boolExpression#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.s2c.sQL.boolExpression#getRhs()
   * @see #getboolExpression()
   * @generated
   */
  EReference getboolExpression_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.s2c.sQL.Term <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Term</em>'.
   * @see org.xtext.example.s2c.sQL.Term
   * @generated
   */
  EClass getTerm();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.Term#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.s2c.sQL.Term#getLhs()
   * @see #getTerm()
   * @generated
   */
  EReference getTerm_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.Term#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.s2c.sQL.Term#getRhs()
   * @see #getTerm()
   * @generated
   */
  EReference getTerm_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.s2c.sQL.Factor <em>Factor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Factor</em>'.
   * @see org.xtext.example.s2c.sQL.Factor
   * @generated
   */
  EClass getFactor();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.Factor#getFactor <em>Factor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Factor</em>'.
   * @see org.xtext.example.s2c.sQL.Factor#getFactor()
   * @see #getFactor()
   * @generated
   */
  EReference getFactor_Factor();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.Factor#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see org.xtext.example.s2c.sQL.Factor#getExpr()
   * @see #getFactor()
   * @generated
   */
  EReference getFactor_Expr();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.Factor#getBinexp <em>Binexp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Binexp</em>'.
   * @see org.xtext.example.s2c.sQL.Factor#getBinexp()
   * @see #getFactor()
   * @generated
   */
  EReference getFactor_Binexp();

  /**
   * Returns the meta object for class '{@link org.xtext.example.s2c.sQL.Binary <em>Binary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Binary</em>'.
   * @see org.xtext.example.s2c.sQL.Binary
   * @generated
   */
  EClass getBinary();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.Binary#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.s2c.sQL.Binary#getLhs()
   * @see #getBinary()
   * @generated
   */
  EReference getBinary_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.Binary#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.s2c.sQL.Binary#getRhs()
   * @see #getBinary()
   * @generated
   */
  EReference getBinary_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.s2c.sQL.Column <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Column</em>'.
   * @see org.xtext.example.s2c.sQL.Column
   * @generated
   */
  EClass getColumn();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.s2c.sQL.Column#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.s2c.sQL.Column#getName()
   * @see #getColumn()
   * @generated
   */
  EAttribute getColumn_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.s2c.sQL.group_clause <em>group clause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>group clause</em>'.
   * @see org.xtext.example.s2c.sQL.group_clause
   * @generated
   */
  EClass getgroup_clause();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.s2c.sQL.group_clause#getExpressions <em>Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressions</em>'.
   * @see org.xtext.example.s2c.sQL.group_clause#getExpressions()
   * @see #getgroup_clause()
   * @generated
   */
  EReference getgroup_clause_Expressions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.s2c.sQL.having_clause <em>having clause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>having clause</em>'.
   * @see org.xtext.example.s2c.sQL.having_clause
   * @generated
   */
  EClass gethaving_clause();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.having_clause#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see org.xtext.example.s2c.sQL.having_clause#getExpr()
   * @see #gethaving_clause()
   * @generated
   */
  EReference gethaving_clause_Expr();

  /**
   * Returns the meta object for class '{@link org.xtext.example.s2c.sQL.expression <em>expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>expression</em>'.
   * @see org.xtext.example.s2c.sQL.expression
   * @generated
   */
  EClass getexpression();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.s2c.sQL.expression#getCol <em>Col</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Col</em>'.
   * @see org.xtext.example.s2c.sQL.expression#getCol()
   * @see #getexpression()
   * @generated
   */
  EReference getexpression_Col();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SQLFactory getSQLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.s2c.sQL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.s2c.sQL.impl.ModelImpl
     * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STATEMENTS = eINSTANCE.getModel_Statements();

    /**
     * The meta object literal for the '{@link org.xtext.example.s2c.sQL.impl.selectImpl <em>select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.s2c.sQL.impl.selectImpl
     * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getselect()
     * @generated
     */
    EClass SELECT = eINSTANCE.getselect();

    /**
     * The meta object literal for the '<em><b>Expressions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__EXPRESSIONS = eINSTANCE.getselect_Expressions();

    /**
     * The meta object literal for the '<em><b>From section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__FROM_SECTION = eINSTANCE.getselect_From_section();

    /**
     * The meta object literal for the '<em><b>Where section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__WHERE_SECTION = eINSTANCE.getselect_Where_section();

    /**
     * The meta object literal for the '<em><b>Group section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__GROUP_SECTION = eINSTANCE.getselect_Group_section();

    /**
     * The meta object literal for the '<em><b>Having section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__HAVING_SECTION = eINSTANCE.getselect_Having_section();

    /**
     * The meta object literal for the '{@link org.xtext.example.s2c.sQL.impl.fromSectionImpl <em>from Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.s2c.sQL.impl.fromSectionImpl
     * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getfromSection()
     * @generated
     */
    EClass FROM_SECTION = eINSTANCE.getfromSection();

    /**
     * The meta object literal for the '<em><b>From item</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FROM_SECTION__FROM_ITEM = eINSTANCE.getfromSection_From_item();

    /**
     * The meta object literal for the '{@link org.xtext.example.s2c.sQL.impl.fromItemImpl <em>from Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.s2c.sQL.impl.fromItemImpl
     * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getfromItem()
     * @generated
     */
    EClass FROM_ITEM = eINSTANCE.getfromItem();

    /**
     * The meta object literal for the '<em><b>Table name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FROM_ITEM__TABLE_NAME = eINSTANCE.getfromItem_Table_name();

    /**
     * The meta object literal for the '<em><b>Select expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FROM_ITEM__SELECT_EXPR = eINSTANCE.getfromItem_Select_expr();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FROM_ITEM__RHS = eINSTANCE.getfromItem_Rhs();

    /**
     * The meta object literal for the '<em><b>Bool expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FROM_ITEM__BOOL_EXPR = eINSTANCE.getfromItem_Bool_expr();

    /**
     * The meta object literal for the '{@link org.xtext.example.s2c.sQL.impl.where_clauseImpl <em>where clause</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.s2c.sQL.impl.where_clauseImpl
     * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getwhere_clause()
     * @generated
     */
    EClass WHERE_CLAUSE = eINSTANCE.getwhere_clause();

    /**
     * The meta object literal for the '<em><b>Bool expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHERE_CLAUSE__BOOL_EXPR = eINSTANCE.getwhere_clause_Bool_expr();

    /**
     * The meta object literal for the '{@link org.xtext.example.s2c.sQL.impl.boolExpressionImpl <em>bool Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.s2c.sQL.impl.boolExpressionImpl
     * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getboolExpression()
     * @generated
     */
    EClass BOOL_EXPRESSION = eINSTANCE.getboolExpression();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_EXPRESSION__LHS = eINSTANCE.getboolExpression_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_EXPRESSION__RHS = eINSTANCE.getboolExpression_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.s2c.sQL.impl.TermImpl <em>Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.s2c.sQL.impl.TermImpl
     * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getTerm()
     * @generated
     */
    EClass TERM = eINSTANCE.getTerm();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERM__LHS = eINSTANCE.getTerm_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERM__RHS = eINSTANCE.getTerm_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.s2c.sQL.impl.FactorImpl <em>Factor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.s2c.sQL.impl.FactorImpl
     * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getFactor()
     * @generated
     */
    EClass FACTOR = eINSTANCE.getFactor();

    /**
     * The meta object literal for the '<em><b>Factor</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTOR__FACTOR = eINSTANCE.getFactor_Factor();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTOR__EXPR = eINSTANCE.getFactor_Expr();

    /**
     * The meta object literal for the '<em><b>Binexp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTOR__BINEXP = eINSTANCE.getFactor_Binexp();

    /**
     * The meta object literal for the '{@link org.xtext.example.s2c.sQL.impl.BinaryImpl <em>Binary</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.s2c.sQL.impl.BinaryImpl
     * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getBinary()
     * @generated
     */
    EClass BINARY = eINSTANCE.getBinary();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINARY__LHS = eINSTANCE.getBinary_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINARY__RHS = eINSTANCE.getBinary_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.s2c.sQL.impl.ColumnImpl <em>Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.s2c.sQL.impl.ColumnImpl
     * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getColumn()
     * @generated
     */
    EClass COLUMN = eINSTANCE.getColumn();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN__NAME = eINSTANCE.getColumn_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.s2c.sQL.impl.group_clauseImpl <em>group clause</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.s2c.sQL.impl.group_clauseImpl
     * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getgroup_clause()
     * @generated
     */
    EClass GROUP_CLAUSE = eINSTANCE.getgroup_clause();

    /**
     * The meta object literal for the '<em><b>Expressions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GROUP_CLAUSE__EXPRESSIONS = eINSTANCE.getgroup_clause_Expressions();

    /**
     * The meta object literal for the '{@link org.xtext.example.s2c.sQL.impl.having_clauseImpl <em>having clause</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.s2c.sQL.impl.having_clauseImpl
     * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#gethaving_clause()
     * @generated
     */
    EClass HAVING_CLAUSE = eINSTANCE.gethaving_clause();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HAVING_CLAUSE__EXPR = eINSTANCE.gethaving_clause_Expr();

    /**
     * The meta object literal for the '{@link org.xtext.example.s2c.sQL.impl.expressionImpl <em>expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.s2c.sQL.impl.expressionImpl
     * @see org.xtext.example.s2c.sQL.impl.SQLPackageImpl#getexpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getexpression();

    /**
     * The meta object literal for the '<em><b>Col</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__COL = eINSTANCE.getexpression_Col();

  }

} //SQLPackage
