/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.s2c.sQL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>where clause</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.s2c.sQL.where_clause#getBool_expr <em>Bool expr</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.s2c.sQL.SQLPackage#getwhere_clause()
 * @model
 * @generated
 */
public interface where_clause extends EObject
{
  /**
   * Returns the value of the '<em><b>Bool expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool expr</em>' containment reference.
   * @see #setBool_expr(boolExpression)
   * @see org.xtext.example.s2c.sQL.SQLPackage#getwhere_clause_Bool_expr()
   * @model containment="true"
   * @generated
   */
  boolExpression getBool_expr();

  /**
   * Sets the value of the '{@link org.xtext.example.s2c.sQL.where_clause#getBool_expr <em>Bool expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool expr</em>' containment reference.
   * @see #getBool_expr()
   * @generated
   */
  void setBool_expr(boolExpression value);

} // where_clause
