/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.sql;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>from Section</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sql.fromSection#getFromItem <em>From Item</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sql.SqlPackage#getfromSection()
 * @model
 * @generated
 */
public interface fromSection extends EObject
{
  /**
   * Returns the value of the '<em><b>From Item</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Item</em>' containment reference.
   * @see #setFromItem(FromItem)
   * @see org.xtext.example.mydsl.sql.SqlPackage#getfromSection_FromItem()
   * @model containment="true"
   * @generated
   */
  FromItem getFromItem();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sql.fromSection#getFromItem <em>From Item</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Item</em>' containment reference.
   * @see #getFromItem()
   * @generated
   */
  void setFromItem(FromItem value);

} // fromSection
