/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.sql.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.sql.IsNullExpression;
import org.xtext.example.mydsl.sql.SqlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Is Null Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IsNullExpressionImpl extends ExpressionImpl implements IsNullExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IsNullExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SqlPackage.Literals.IS_NULL_EXPRESSION;
  }

} //IsNullExpressionImpl
